### ISSUE TITLE
Clévison Barbosa [PHP][PYTHON] [BACKEND] 

### ISSUE THREAD

**Issue by clevisonbarbosa** [devssa/me-contrata#33]
<!--
  ==========
## Nome completo

 Clévison Barbosa 

## Localidade

 Feira de Santana

## Apresentação
Sou formado em tecnólogo em logística, cursando analise e desenvolvimento de sistemas.
Fiz freela em python + django, e tenho como stack também php e laravel.
Estou a procura do primeiro job na área.

## Outras Informações

 Estou totalmente disponível em horário integral, apto a trabalho remoto, pois já atuei com git/github para equipe, e dependendo, até uma mudança de cidade.

## Especialidades

- Python
- JavaScript
- HTML
- CSS
- PHP
- Linux
- Bootstrap
- Git
- MySQL
- Postgresql

## Nível

- [ ] Estágio
- [x] Júnior
- [ ] Pleno
- [ ] Sênior

## Tipo de contratação

- [x] PJ
- [x] CLT
- [x] Freela

## Tipo de trabalho

- [x] Remoto - Parcial
- [x] Remoto - Total
- [x] Alocado

## Contato

 
https://www.linkedin.com/in/clevison-barbosa-ba444818a/

## Site

https://github.com/clevisonbarbosa/ClevisonBarbosa

**Comment by devssa** [comment]
Issue vazia
